### ISSUE TITLE
TODO for 1.0.0

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/nix-test-runner#1]
- [x] nicer error handling
- [x] better README

**Comment by stoeffel** [comment]
- [x] diffing
- [x] write xml/json to file
- [x] fix relative path use path mod instead of string
